name: CICD

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip.exec
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.FOZZY_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
         
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
        
      - name: copy jar
        run: scp target/scoreboard-1.0.jar root@23.105.226.90:/opt/
      
      - name: kill
        run: ssh root@23.105.226.90 'pkill -f java'
        
      - name: Deploy
        run: ssh root@23.105.226.90 'nohup java -jar /opt/scoreboard-1.0.jar > /dev/null 2>&1 &'
        
