name: CICD

on:
  [push]
#     branches: -masret

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v1
        
#       - name: Build with Maven
#         run: mvn package -Dmaven.test.skip.exec
        
      - name: LL
        run: ssh root@23.105.226.90
        
      - name: UU
        run: ls
    
    
    
    
    
#     permissions:
#       contents: read
#       packages: write

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
