name: CICD

on:
  [push]
#     branches: -masret

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip.exec
        
#       - name: S1
#         run: pwd
        
#       - name: S2
#         run: ls
        
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{secrets.FOZZY_KEY}}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      
      - name: Deploy
#         run: scp /home/runner/work/scoreboard/scoreboard/target.scoreboard-1.0.jar root@23.105.226.90:opt/ppp/
        run: rsync -e "ssh "${{secrets.FOZZY_KEY}}" StrictHostKeyChecking=no" --archive --verbose --progress /home/runner/work/scoreboard/scoreboard/target.scoreboard-1.0.jar root@23.105.226.90:opt/ppp/
    
    
    
    
    
#     permissions:
#       contents: read
#       packages: write

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
